---

- name: Copy over new code
  hosts: project-server
  tasks:
        - name: Copy over project dir
          copy:
                src: F20-Team15-Hastings.Gaber.Gleaton.Sherrer/project
                dest: ~/project/
        - name: Copy over .py files in repo
          copy:
                src: F20-Team15-Hastings.Gaber.Gleaton.Sherrer/*.py
                dest: ~/project/

- name: Deploy new code
  hosts: project-server
  become: true
  tasks:
        - name: Stop project service
          systemd: state=stopped name=project
        - name: Start project service
          systemd: state=started name=project
